name = "PkgTPL"
uuid = "c7410679-6c1e-4839-8975-fcd3532f9136"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]
version = "0.1.0"

[deps]

[compat]
Documenter = "0.24"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
